---
title: "Proyecto"
output: html_notebook
---

```{r}
library(easypackages)
librerias <- c("GEOquery","Biobase","BiocGenerics","magrittr","tidyr","dplyr","stringr","limma","EnhancedVolcano", "purrr","foreach","tidyverse", "xlsx","Hmisc", "tidyverse", "data.table", "PAA")
libraries(librerias)
```

```{r}
#Armar mi ruta
pth <- file.path(getwd(), "mis_gse_data_1.rds")
path <- file.path(getwd(), "mis_target.rds")
saving <- file.path(getwd(), "tabla_targets.rds")
```


```{r}
my_getGEO <- function (codigo_gse){
  try(getGEO(codigo_gse, GSEMatrix = TRUE, AnnotGPL = TRUE, getGPL = TRUE) -> my.gse.data)
  try(my.gse.data %<>% names %>% str_extract('GSE\\d+(-GPL\\d+)?') %>% set_names(my.gse.data,.))
  return(my.gse.data)}
mis.codigos.gse <- c('GSE1012','GSE1031','GSE6105','GSE6350','GSE9595','GSE10272','GSE6924','GSE13994','GSE15328','GSE19049','GSE19630','GSE20310','GSE18219','GSE19646','GSE26984','GSE28843','GSE30426','GSE30426','GSE28357','GSE34745','GSE35184','GSE35448','GSE35633','GSE35804','GSE36072','GSE36332','GSE38763','GSE40733','GSE26651','GSE39274','GSE42263','GSE42847','GSE44352','GSE47057','GSE51603','GSE51839','GSE56487','GSE43255','GSE45163','GSE58823','GSE87920','GSE101695','GSE140756')
mis_gse_data_1 <- map(mis.codigos.gse, my_getGEO) %>% unlist 


saveRDS(mis_gse_data_1, pth)

```

```{r}
titulos                 <- data.frame()
list_con_eset_filtrados <- list()
RDS<- readRDS(pth)
b <- RDS %>% names

for(i in 1:length(b)) {
  if  (b[i]=="GSE6105"|b[i]=="GSE6350"){
       RDS[[i]]  -> mi.gse;                                                                                         ####OK
       pData(mi.gse) %>% filter(str_detect(title,'control|infection')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
    
  }
  else if (b[i]=="GSE51603"){
    RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(title, '21dpi|1dpi')) %>%rownames() %>% mi.gse[, .] -> un_eset_filtrado
  }
  else if (b[i]=="GSE19646"){
    RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(source_name_ch1, 'CONTROL|INFECTED')& str_detect(source_name_ch1 ,'EXPOSED', negate = T)) %>%rownames() %>% mi.gse[, .] -> un_eset_filtrado
  }
    else if (b[i]== "GSE44352-GPL14875"|b[i] == "GSE44352-GPL15180'") {
       RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(title,'zebrafish')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
    }
  else if (b[i]=="GSE19049"){
    RDS[[i]] -> mi.gse; pData(mi.gse) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ## no filters requiered unless we want to filter by organ 
  }
    else if (b[i] == "GSE1012"| b[i]== "GSE1031"){
     RDS[[i]]  -> mi.gse; pData(mi.gse) %>%filter(str_detect(source_name_ch1,'(?i)Non-infected|Piscirickettsia')& str_detect(source_name_ch2,'(?i)Non-infected|(?i)Piscirickettsia')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
    }
    else if (b[i] == "GSE6924-GPL2899"){
       RDS[[i]]  -> mi.gse; pData(mi.gse) %>%filter(str_detect(title,'day5|day9')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
    }
    else if (b[i] == "GSE6924-GPL3976"){
       RDS[[i]]  -> mi.gse; pData(mi.gse) %>%filter(str_detect(title,'controls') | str_detect(title, 'day1', negate= T)) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
        }
 
  else if (b[i] == "GSE9595"){
     RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(title,'AGD'))  %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE10272"){ 
    RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(title,'72h') & str_detect(title, 'attenuated', negate = T)) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE13994"){
       RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(title,'24hpi')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE15328"){
      RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(title,'120hpi|6dpi|control|PBS')& str_detect(title, '.*CR.*', negate = T)) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE19630"){
       RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(title,'16j|7j')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE20310"){
      RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(title,'Infected|Not.infected')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE18219" | b[i] == "GSE19646"){
      RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(source_name_ch1,'(?i)control|infected') & str_detect(source_name_ch1,'(?i)exposed', negate = T)) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE26984"){
      RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(source_name_ch1,'infected')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE28843-GPL10679"){
     RDS[[i]]  -> mi.gse; pData(mi.gse) %>%  filter(str_detect(title,'Heart.*4.wpi',negate = T) & str_detect(title, '4.wpi|10.wpi')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE28843-GPL10705"){
      RDS[[i]]  -> mi.gse; pData(mi.gse) %>%  filter(str_detect(title,'8 wpi')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE30426"){
      RDS[[i]]  -> mi.gse; pData(mi.gse) %>%  filter(str_detect(source_name_ch1,'3 p.i|not infected')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE28357"){
      RDS[[i]]  -> mi.gse; pData(mi.gse) %>%  filter(str_detect(title,'0h|63d')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE34745"){
     RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(source_name_ch1,'Infected, Day 4|Control, Day 4')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE35184"){
     RDS[[i]]  -> mi.gse; pData(mi.gse) %>%  filter(str_detect(source_name_ch1,'control|25')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE35448"){
    RDS[[i]]  -> mi.gse; pData(mi.gse) %>%  filter(str_detect(title,'Susceptible')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE35804"){
      RDS[[i]]  -> mi.gse; pData(mi.gse) %>%  filter(str_detect(title,'Naive')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE35633"){
      RDS[[i]]  -> mi.gse; pData(mi.gse) %>%  filter(str_detect(source_name_ch1,'late infected|control')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE36332"){
    RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(title,'Unvaccinated')) %>% filter(str_detect(title, '0h|72h')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE38763"){
     RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(title,'No estrogen')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE40733"){
     RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(title,'12h')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE26651"){
     RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(title,'day2')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE39274"){
    RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(title,'mutant', negate =T)) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE42263"){
     RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(title,'non-infected') | str_detect(title, 'infected')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE42847-GPL14875"){
    RDS[[i]]  -> mi.gse; pData(mi.gse) %>%  filter(str_detect(title,'Non-injected|5 DPI')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE42847-GPL15180"){
    RDS[[i]]  -> mi.gse; pData(mi.gse) %>%  filter(str_detect(title,'126HPI|102HPI')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE47057"){
     RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(title,'infected')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE51839"){
    RDS[[i]]  -> mi.gse; pData(mi.gse) %>%  filter(str_detect(title,'Unvaccinated|Control')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
   else if (b[i] == "GSE56487"){
     RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(source_name_ch1,'-injected') & str_detect(source_name_ch1,'vaccine', negate = T)) %>% filter(str_detect(source_name_ch1, '72hpi')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
   }
   else if (b[i] == "GSE43255"){
     RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(title, 'High')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
   }
   else if (b[i] == "GSE45163"){
    RDS[[i]]  -> mi.gse; pData(mi.gse) %>%  filter(str_detect(title,'Control|12h after')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
   }
   else if (b[i] == "GSE58823"){
     RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(title,'Control|VHSV')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
   }
   else if (b[i] == "GSE87920"){
    RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(source_name_ch1,'fed control')) %>% filter(str_detect(source_name_ch1,'20 days post challenge.')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
   }
  else if (b[i] == "GSE101695"){
    RDS[[i]]  -> mi.gse; pData(mi.gse) %>%  filter(str_detect(characteristics_ch1.1,'control|infected')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE26981"){
     RDS[[i]]  -> mi.gse; pData(mi.gse) %>%  filter(str_detect(title,'10|15')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado ####OK
  }
  else if (b[i] == "GSE42491"){
     RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(source_name_ch1,'24h|12h') & str_detect(source_name_ch2,'24h|12h')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado
  }
  else if (b[i] == "GSE3857"){
     RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(source_name_ch1,'control|exposed') & str_detect(source_name_ch2,'control|exposed')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado
  }
  else if (b[i] == "GSE36072"){
     RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(title,'Placebo')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado
  }
  else if (b[i] == "GSE122142"){
     RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(title,'Before') | str_detect(title,'36|43|57')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado
  }
  else if (b[i] == "GSE32119-GPL14575"| b[i]== "GSE32119-GPL6457"){
     RDS[[i]]  -> mi.gse; pData(mi.gse) %>% filter(str_detect(title,'(18|16)hpi')) %>% rownames %>% mi.gse[, .] -> un_eset_filtrado
  }
  
   titulos <- bind_rows(titulos,pData(un_eset_filtrado) )

   list_con_eset_filtrados[[b[i]]] <- un_eset_filtrado
}


list_con_eset_filtrados %>% map(pData) %>% enframe%>%  unnest %>% 
                     dplyr::select(matches('^name$|title|geo|source|characteristics|organism')) -> GSMs_filtrados

##escritura excel cambiar directorio ##
xlsx::write.xlsx2(GSMs_filtrados, "Excel.xlsx")
```

```{r}
### Target generations
## la informacion de los tejidos podria se agregadas 
list_con_eset_filtrados$`GSE6924-GPL3976` -> un_estudio


un_estudio     %>% pData %>% dplyr::select(matches('source.*ch') | matches('geo')| matches('label')) -> para_targets_0

para_targets_0 %>% mutate_at('source_name_ch1', ~str_replace(.,'.*control.*','control'))%>% 
                   mutate_at('source_name_ch1', ~str_replace(.,'.*challenged.*','infected'))%>% 
                   mutate_at('source_name_ch2', ~str_replace(.,'.*reference.*','control'))%>% 
                   unite("Alexa 555", source_name_ch1,label_ch1, sep ="-")%>% 
                   unite("Alexa 647", source_name_ch2,label_ch2, sep ="-")  %>%
                     mutate_at('Alexa 555', ~str_extract(.,".*(?=-Alexa)")) %>%
                     mutate_at('Alexa 647', ~str_extract(.,".*(?=-Alexa)")) %>% 
                     select(matches('alexa|geo')) -> 'GSE6924-GPL3976'
####Sin dye swap
list_con_eset_filtrados$`GSE6924-GPL2899` -> un_estudio
un_estudio%>% pData %>% select(matches('source.*ch') | matches('geo')| matches('label')) %>% unite("Alexa 555",source_name_ch1) %>% unite("Alexa 647",source_name_ch2) %>%  mutate_at('Alexa 555', ~str_replace(.,'.*necrosis.*','infected')) %>% mutate_at('Alexa 647', ~str_replace(.,'.*reference.*','control')) %>% select(matches('geo')|matches('Alexa')) -> `GSE6924-GPL2899`  

```

```{r}
#DYE SWAP, Reference sera considerado como control, puesto que sera una mezcla de todos los RNA
list_con_eset_filtrados$GSE19646 -> un_estudio
un_estudio     %>% pData %>% dplyr::select(matches('source.*ch') | matches('geo')| matches('label')) %>% mutate_at('source_name_ch1', ~str_replace(.,'.*CONTROL.*','control'))%>%mutate_at('source_name_ch1', ~str_replace(.,'.*INFECTED.*','infected'))%>% mutate_at('source_name_ch2',~str_replace(.,'.*REFERENCE.*','control'))%>% unite("Channel 1", source_name_ch1,label_ch1, sep ="-") %>%                             unite("Channel 2", source_name_ch2,label_ch2, sep ="-") %>% mutate(Cy5= ifelse( str_detect(`Channel 1`, "Cy5"), .[["Channel 1"]], .[["Channel 2"]]  ) ) %>% 
mutate(Cy3= ifelse( str_detect(`Channel 2`, "Cy3"), .[["Channel 2"]], .[["Channel 1"]]  ) ) %>%select(matches("cy|geo"))%>% 
                             mutate_at('Cy5', ~str_replace(.,'.*control.*','control'))%>% 
                             mutate_at('Cy5', ~str_replace(.,'.*infected.*','infected')) %>% 
                             mutate_at('Cy3', ~str_replace(.,'.*control.*','control'))%>% 
                             mutate_at('Cy3', ~str_replace(.,'.*infected.*','infected')) -> GSE19646
                  

```


```{r}
#Dye swap
list_con_eset_filtrados$GSE18219 -> un_estudio
un_estudio     %>% pData %>% dplyr::select(matches('source.*ch') | matches('geo')| matches('label')) %>% 
                             mutate_at('source_name_ch1', ~str_replace(.,'.*control.*','control')) %>%
                             mutate_at('source_name_ch1', ~str_replace(.,'.*infected.*','infected'))%>%
                             mutate_at('source_name_ch2', ~str_replace(.,'.*reference.*','control')) %>% 
                                    unite("Channel 1", source_name_ch1,label_ch1, sep ="-") %>%
                                     unite("Channel 2", source_name_ch2,label_ch2, sep ="-") %>% 
                                     select(matches("channel|geo")) -> df

df %>% mutate(Cy5= ifelse( str_detect(`Channel 1`, "Cy5"), .[["Channel 1"]], .[["Channel 2"]]  ) ) %>% 
mutate(Cy3= ifelse( str_detect(`Channel 2`, "Cy3"), .[["Channel 2"]], .[["Channel 1"]]  ) ) %>%select(matches("cy|geo"))%>% 
                             mutate_at('Cy5', ~str_replace(.,'.*control.*','control'))%>% 
                             mutate_at('Cy5', ~str_replace(.,'.*infected.*','infected')) %>% 
                             mutate_at('Cy3', ~str_replace(.,'.*control.*','control'))%>% 
                             mutate_at('Cy3', ~str_replace(.,'.*infected.*','infected'))-> GSE18219
```


```{r}
##sin dyeswap
list_con_eset_filtrados$GSE1031 -> un_estudio 
un_estudio %>% pData %>% select(matches('geo')| matches('source.*ch')) %>% unite("Cy3",source_name_ch1) %>%unite("Cy5",source_name_ch2) %>%  mutate_at('Cy3', ~str_replace(.,'.*Non-infected.*', 'control')) %>% mutate_at('Cy3', ~str_replace(.,'.*salmonis-infected.*', 'infected')) %>% mutate_at('Cy5', ~str_replace(.,'.*Non-infected.*', 'control')) %>% mutate_at('Cy5', ~str_replace(.,'.*salmonis-infected.*', 'infected')) %>% select(matches('geo')|matches('cy')) -> GSE1031 
```

```{r}
#sin dye swap
list_con_eset_filtrados$GSE1012 -> un_estudio 
un_estudio %>% pData %>% select(matches('geo')| matches('source.*ch')) %>% unite("Cy3",source_name_ch1) %>%unite("Cy5",source_name_ch2) %>%  mutate_at('Cy3', ~str_replace(.,'(?i).*Non-infected.*', 'control')) %>% mutate_at('Cy3', ~str_replace(.,'.*salmonis-infected.*', 'infected')) %>% mutate_at('Cy5', ~str_replace(.,'(?i).*Non-infected.*', 'control')) %>% mutate_at('Cy5', ~str_replace(.,'.*salmonis-infected.*', 'infected')) -> GSE1012
```

```{r}
#single channel 
list_con_eset_filtrados$GSE6350 -> un_estudio 
un_estudio %>% pData %>% select(matches('source.*ch') | matches('geo')| matches('label')) %>%  mutate_at('source_name_ch1', ~str_replace(.,'.*control.*','control')) %>% mutate_at('source_name_ch1', ~str_replace(.,'.*infection.*','infected')) %>% mutate(Biotin = source_name_ch1) %>% select(matches("geo|bio")) -> GSE6350
```

```{r}
#Sin dyeswap y no es posible eliminar la covariable lesion
#list_con_eset_filtrados$GSE9595 -> un_estudio 
#un_estudio %>% pData %>% select(matches('source.*ch') | matches('geo')| matches('label')) %>% mutate_at()
```

```{r}
##Sin dye swap, Recordar que se esta considerando el virus no atenuado como "infected" y LPS como control  
list_con_eset_filtrados$GSE10272 -> un_estudio 
un_estudio %>% pData %>% select(matches('source.*ch') | matches('geo')| matches('label')) %>%  mutate_at('source_name_ch1', ~str_replace(.,'.*LPS.*','control')) %>%  mutate_at('source_name_ch2', ~str_replace(.,'.*LPS.*','control')) %>%  mutate_at('source_name_ch1', ~str_replace(.,'.*IHNV.*','infected')) %>% mutate_at('source_name_ch2', ~str_replace(.,'.*IHNV.*','infected')) %>% unite("Cy5", source_name_ch1,label_ch1, sep ="-") %>%unite("Cy3", source_name_ch2,label_ch2, sep ="-")  %>%  mutate_at('Cy5', ~str_replace(.,'.*control.*','control'))%>% mutate_at('Cy5', ~str_replace(.,'.*infected.*','infected')) %>% mutate_at('Cy3', ~str_replace(.,'.*control.*','control'))%>% mutate_at('Cy3', ~str_replace(.,'.*infected.*','infected')) %>% select(matches('geo')|matches('cy')) -> GSE10272
```

```{r}
#sin dye swap, source name ch1 tiene solo CR "common reference" = mezcla de todos los RNAS del studio, lo que sera tomado como control (embriones inyectados 27 horas post fertilizacion (criterios morfologicos) con PBS o Salmonelas)
list_con_eset_filtrados$GSE13994 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')| matches('title')) %>% mutate_at('source_name_ch1', ~str_replace(.,'.*', 'control')) %>% mutate_at('source_name_ch2',~str_replace(.,'.*PBS.*','control')) %>% mutate_at('source_name_ch2',~str_replace(.,'.*24hpi.*','infected')) %>% unite("Cy3", source_name_ch1,label_ch1, sep ="-") %>% unite("Cy5", source_name_ch2,label_ch2, sep ="-") %>%select(matches("cy|geo")) %>% mutate_at('Cy5', ~str_replace(.,'.*control.*','control'))%>% 
                             mutate_at('Cy5', ~str_replace(.,'.*infected.*','infected')) %>% 
                             mutate_at('Cy3', ~str_replace(.,'.*control.*','control')) -> GSE13994
```

```{r}
### podria ser util solo dejar los controles (PBS)  vs infectados cronicos eliminando todos los Common reference (Filtro arreglado )
## sin dye swap
list_con_eset_filtrados$GSE15328 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')| matches('title')) %>% unite("Cy3", source_name_ch1,label_ch1) %>% unite("Cy5", source_name_ch2,label_ch2) %>% mutate_at("Cy3",~str_replace(.,'.*control.*', 'control')) %>% mutate_at("Cy5",~str_replace(.,'.*infected.*', 'infected')) %>% select(matches('geo')|matches('cy')) -> GSE15328
```

```{r}
#single channel 
list_con_eset_filtrados$GSE19049 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')| matches('title')) %>% unite('Cy3', source_name_ch1,label_ch1) %>% select(matches('cy3')| matches('geo')) %>% mutate_at('Cy3', ~str_replace(.,".*infection.*","infected")) %>% mutate_at('Cy3', ~str_replace(.,".*control.*","control")) -> GSE19049
```

```{r}
#no dye swap, en este caso los Rna's de referencia son 18 salmones sanos por lo tanto seran considerados como control
list_con_eset_filtrados$GSE19630 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite('Alexa 555', source_name_ch1,label_ch1) %>% unite("Alexa 647", source_name_ch2,label_ch2) %>% mutate_at('Alexa 555', ~str_replace(.,".*control.*","control"))%>% mutate_at('Alexa 555', ~str_replace(.,".*infected.*","infected")) %>%  mutate_at('Alexa 647', ~str_replace(.,".*reference.*","control")) %>% select(matches('geo')|matches('Alexa')) -> GSE19630
```

```{r}
#single channel 
list_con_eset_filtrados$GSE20310 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite('Cy3', source_name_ch1,label_ch1) %>% mutate_at('Cy3', ~str_replace(.,".*S.th.*", "infected")) %>% mutate_at('Cy3', ~str_replace(.,".*PBS.*", "control")) %>% select(matches('geo')|matches('cy')) -> GSE20310
```

```{r}
##Dye SWap, reference Rna = mezcla de todos los RNA seran considerados como control
list_con_eset_filtrados$GSE18219 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite('Channel 1', source_name_ch1,label_ch1) %>% unite('Channel 2',source_name_ch2,label_ch2)%>% mutate(Cy5= ifelse( str_detect(`Channel 1`, "Cy5"), .[["Channel 1"]], .[["Channel 2"]]  ) ) %>% 
mutate(Cy3= ifelse( str_detect(`Channel 2`, "Cy3"), .[["Channel 2"]], .[["Channel 1"]]  ) ) %>%select(matches("cy|geo")) %>% mutate_at('Cy3', ~str_replace(.,"(?i).*reference pool.*", "control")) %>% mutate_at('Cy3', ~str_replace(.,"(?i).*infected.*", "infected")) %>%mutate_at('Cy3', ~str_replace(.,"(?i).*control.*", "control")) %>%  mutate_at('Cy5', ~str_replace(.,"(?i).*reference pool.*", "control")) %>% mutate_at('Cy5', ~str_replace(.,"(?i).*control.*", "control")) %>% mutate_at('Cy5', ~str_replace(.,"(?i).*infected.*", "infected")) -> GSE18219
```

```{r}
#dyeswap, reference = mezcla de todos los RNA's 
list_con_eset_filtrados$GSE19646 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite('Channel 1', source_name_ch1,label_ch1) %>% unite('Channel 2',source_name_ch2,label_ch2)%>% mutate(Cy5= ifelse( str_detect(`Channel 1`, "Cy5"), .[["Channel 1"]], .[["Channel 2"]]  ) ) %>% 
mutate(Cy3= ifelse( str_detect(`Channel 2`, "Cy3"), .[["Channel 2"]], .[["Channel 1"]]  ) ) %>%select(matches("cy|geo")) %>% mutate_at('Cy3', ~str_replace(.,".*PATHOGEN.*", "control")) %>% mutate_at('Cy3', ~str_replace(.,"(?i).*infected.*", "infected")) %>%mutate_at('Cy3', ~str_replace(.,"(?i).*control.*", "control")) %>%  mutate_at('Cy5', ~str_replace(.,"(?i).*pathogen.*", "control")) %>% mutate_at('Cy5', ~str_replace(.,"(?i).*control.*", "control")) %>% mutate_at('Cy5', ~str_replace(.,"(?i).*infected.*", "infected")) -> GSE19646
```

```{r}
#estudio hermoso
list_con_eset_filtrados$GSE26984 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite("Cy5", source_name_ch1,label_ch1) %>% unite("Cy3", source_name_ch2,label_ch2) %>% mutate_at("Cy3",~str_replace(.,'.*control.*', 'control')) %>% mutate_at("Cy5",~str_replace(.,'.*infected.*', 'infected')) %>% select(matches('geo')| matches('cy')) -> GSE26984
```

```{r}
##sin DYE swap
list_con_eset_filtrados$`GSE28843-GPL10679` -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label'))%>% unite("Cy5", source_name_ch1,label_ch1) %>% unite("Cy3", source_name_ch2,label_ch2) %>% mutate_at("Cy3",~str_replace(.,'.*control.*', 'control')) %>% mutate_at("Cy5",~str_replace(.,'.*infected.*', 'infected')) %>% select(matches('geo')| matches('cy')) -> 'GSE28843-GPL10679'



list_con_eset_filtrados$`GSE28843-GPL10705` -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>%  unite("Cy5", source_name_ch1,label_ch1) %>% unite("Cy3", source_name_ch2,label_ch2) %>% mutate_at("Cy3",~str_replace(.,'.*control.*', 'control')) %>% mutate_at("Cy5",~str_replace(.,'.*infected.*', 'infected')) %>% select(matches('geo')| matches('cy')) ->'GSE28843-GPL10705'
```

```{r}
#No Dye swap, Single channel 
list_con_eset_filtrados$GSE30426 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite("Cy3", source_name_ch1,label_ch1) %>% mutate_at("Cy3",~str_replace(.,'.*infected.*', 'infected')) %>% select(matches('geo')| matches('cy')) -> GSE30426
```

```{r}
list_con_eset_filtrados$GSE28357 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>%  unite("Cy3", source_name_ch1,label_ch1) %>% mutate_at("Cy3",~str_replace(.,'.*63d.*', 'infected')) %>% mutate_at("Cy3",~str_replace(.,'.*0h.*', 'control')) %>%select(matches('geo')| matches('cy'))  -> GSE28357 

```

```{r}
#No Dye Swap
list_con_eset_filtrados$GSE34745 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite("Cy3", source_name_ch1,label_ch1) %>% unite("Cy5", source_name_ch2,label_ch2) %>% mutate_at("Cy3",~str_replace(.,'.*Infected.*', 'infected')) %>% mutate_at("Cy3",~str_replace(.,'.*Control.*', 'control')) %>% mutate_at("Cy5",~str_replace(.,'.*Infected.*', 'infected')) %>% mutate_at("Cy5",~str_replace(.,'.*Control.*', 'control')) %>% select(matches('geo')| matches('cy')) -> GSE34745
```

```{r}
##Single Channel
list_con_eset_filtrados$GSE35184 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite("Cy3", source_name_ch1,label_ch1) %>% mutate_at("Cy3",~str_replace(.,'.*control.*', 'control')) %>% mutate_at("Cy3",~str_replace(.,'.*25.*', 'infected')) %>% select(matches('geo')| matches('cy')) -> GSE35184
```


```{r}
#single channel
list_con_eset_filtrados$GSE35448 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label') |matches('title')) %>% unite("Cy3", title,label_ch1) %>% mutate_at("Cy3",~str_replace(.,'.*Control.*', 'control')) %>% mutate_at("Cy3",~str_replace(.,'.*Infected.*', 'infected')) %>% select(matches('geo')| matches('cy'))-> GSE35448

```

```{r}
list_con_eset_filtrados$GSE35633 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite("Cy3", source_name_ch1,label_ch1) %>% mutate_at("Cy3",~str_replace(.,'.*control.*', 'control')) %>% mutate_at("Cy3",~str_replace(.,'.*infected.*', 'infected')) %>% select(matches('geo')| matches('cy')) -> GSE35633
```

```{r}
#Single channel
list_con_eset_filtrados$GSE35804 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite("Cy3", source_name_ch1,label_ch1) %>% mutate_at("Cy3",~str_replace(.,'.*VHSV.*', 'infected')) %>% mutate_at("Cy3",~str_replace(.,'.*control.*', 'control')) %>% select(matches('geo')| matches('cy')) -> GSE35804
```

```{r}
#Singel Channel
list_con_eset_filtrados$GSE36072 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite("Cy5", source_name_ch1,label_ch1) %>% unite("Cy3", source_name_ch2,label_ch2) %>% mutate_at("Cy5",~str_replace(.,'.*no lice.*', 'control')) %>% mutate_at("Cy5",~str_replace(.,'.*lice.*', 'infected'))%>% mutate_at("Cy5",~str_replace(.,'.*all.*', 'control')) %>% mutate_at("Cy3",~str_replace(.,'.*no lice.*', 'control')) %>% mutate_at("Cy3",~str_replace(.,'.*lice.*', 'infected'))%>% mutate_at("Cy3",~str_replace(.,'.*all.*', 'control')) %>% select(matches('geo')| matches('cy'))-> GSE36072
```

```{r}
#no Dye swap
list_con_eset_filtrados$GSE36332 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>%  unite("Cy5", source_name_ch1,label_ch1) %>%  unite("Cy3", source_name_ch2,label_ch2) %>% mutate_at("Cy5",~str_replace(.,'.*uninfected.*', 'control')) %>% mutate_at("Cy5",~str_replace(.,'.*ruckeri.*', 'infected'))%>% mutate_at("Cy3",~str_replace(.,'.*pooled.*', 'control'))%>% select(matches('geo')| matches('cy')) -> GSE36332
```

```{r}
#no Dye swap
list_con_eset_filtrados$GSE38763 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite("Cy5", source_name_ch1,label_ch1)%>% unite("Cy3", source_name_ch2,label_ch2) %>% mutate_at("Cy5",~str_replace(.,'.*infected.*', 'infected')) %>% mutate_at("Cy3",~str_replace(.,'.*control.*', 'control')) %>% select(matches('geo')| matches('cy')) -> GSE38763
```

```{r}
#DYE Swap
list_con_eset_filtrados$GSE40733 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label'))%>% unite('Channel 1', source_name_ch1,label_ch1) %>% unite('Channel 2',source_name_ch2,label_ch2)%>% mutate(Cy5= ifelse( str_detect(`Channel 1`, "Cy5"), .[["Channel 1"]], .[["Channel 2"]]  ) ) %>% 
mutate(Cy3= ifelse( str_detect(`Channel 2`, "Cy3"), .[["Channel 2"]], .[["Channel 1"]]  ) ) %>%select(matches("cy|geo")) %>% mutate_at("Cy5",~str_replace(.,'.*infection.*', 'infected')) %>% mutate_at("Cy5",~str_replace(.,'.*control.*', 'control')) %>% mutate_at("Cy3",~str_replace(.,'.*infection.*', 'infected')) %>% mutate_at("Cy3",~str_replace(.,'.*control.*', 'control')) ->GSE40733

```

```{r}
#single channel
list_con_eset_filtrados$GSE26651-> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite("Cy3", source_name_ch1,label_ch1) %>% mutate_at("Cy3",~str_replace(.,'.*mock.*', 'control')) %>% mutate_at("Cy3",~str_replace(.,'.*infected.*', 'infected')) %>% select(matches('Cy3')| matches('geo')) -> GSE26651
```

```{r}
#No Dyeswap, Common reference = mixture of all RNA samples from the microarray study, sera considerado como "Control", Et = E.tarda (bacteria infection), St= salmonella thyphi
list_con_eset_filtrados$GSE39274-> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite("Cy3", source_name_ch1,label_ch1) %>% unite("Cy5", source_name_ch2,label_ch2) %>% mutate_at("Cy3",~str_replace(.,'.*rerio.*', 'control')) %>% mutate_at("Cy5",~str_replace(.,'.*PBS.*', 'control')) %>% mutate_at("Cy5",~str_replace(.,'.*Wildtype.*', 'infected')) %>% select(matches('geo')|matches('cy')) ->GSE39274

```

```{r}
#single channel.. Svcv = Spring Viraemia of carp virus viremia primaveral de la carpa 
list_con_eset_filtrados$GSE42263 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite("Cy3", source_name_ch1,label_ch1) %>% mutate_at("Cy3",~str_replace(.,'.*non-infected.*', 'control')) %>% mutate_at("Cy3",~str_replace(.,'.*infected.*', 'infected')) %>% select(matches('cy')| matches('geo')) -> GSE42263
```

```{r}
##Single channel
list_con_eset_filtrados$`GSE42847-GPL14875` -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite("mcherry", source_name_ch1) %>% mutate_at("mcherry",~str_replace(.,'.*Non-injected.*', 'control')) %>% mutate_at("mcherry",~str_replace(.,'.*mcherry.*', 'infected')) ->`GSE42847-GPL14875`

###no Dye Swap, common reference = all RNA samples (1) 20 CFU of S. epidermdis O-47 mCherry bacteria suspended in PVP (Polyvinylpyrrolidone), (2) mock-injected with PVP as a control, (3) Needle insertion as control, (4) Non-injected as a control. At 8 hpf (6 h post infection), 32 hpf (30 h post infection), 56 hpf (54 h post infection), 80 hpf (78 h post infection), 104 hpf (102 h post infection) or 128 hpf (126 h post infection)
list_con_eset_filtrados$`GSE42847-GPL15180` -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label'))%>% unite("Cy3", source_name_ch1,label_ch1)%>% unite("Cy5", source_name_ch2,label_ch2) %>% mutate_at("Cy3",~str_replace(.,'.*CR.*', 'control')) %>% mutate_at("Cy5",~str_replace(.,'.*Non-injected.*', 'control')) %>% mutate_at("Cy5",~str_replace(.,'.*Needle.*', 'control')) %>% mutate_at("Cy5",~str_replace(.,'.*PVP.*', 'control')) %>% mutate_at("Cy5",~str_replace(.,'.*S-epi.*', 'infected')) %>% select(matches('cy')|matches('geo')) -> `GSE42847-GPL15180`
```

```{r}
#single channel, no hay informacion del tipo de DYE
list_con_eset_filtrados$`GSE44352-GPL14875` -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite("channel 1",source_name_ch1) %>% mutate_at("channel 1",~str_replace(.,'.*Mycobacterium.*', 'infected')) %>% mutate_at("channel 1",~str_replace(.,'.*total.*', 'control')) -> `GSE44352-GPL14875`

list_con_eset_filtrados$`GSE44352-GPL15180` -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>%  unite("channel 1",source_name_ch1) %>% mutate_at("channel 1",~str_replace(.,'.*Mycobacterium.*', 'infected')) %>% mutate_at("channel 1",~str_replace(.,'.*total.*', 'control')) -> `GSE44352-GPL15180` 

```

```{r}
#no dyeswap
list_con_eset_filtrados$GSE47057 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite("Cy5",source_name_ch1,label_ch1) %>% unite("Cy3",source_name_ch2,label_ch2)%>% mutate_at("Cy5",~str_replace(.,'.*infected.*', 'infected'))%>% mutate_at("Cy3",~str_replace(.,'.*non infected.*', 'control')) %>% select(matches('cy')| matches('geo')) -> GSE47057
```

```{r}
## 1dpi = control , 21 dpi = infected... Single channel
list_con_eset_filtrados$GSE51603 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite("Cy3",source_name_ch1,label_ch1) %>% mutate_at("Cy3",~str_replace(.,'.*21dpi.*', 'infected')) %>% mutate_at("Cy3",~str_replace(.,'.*1dpi.*', 'control')) %>% select(matches('geo')| matches('cy')) ->GSE51603
```

```{r}
##single channel
list_con_eset_filtrados$GSE51839 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite("Cy3",source_name_ch1,label_ch1) %>% mutate_at("Cy3",~str_replace(.,'.*Control.*', 'control'))%>% mutate_at("Cy3",~str_replace(.,'.*Mock.*', 'control')) %>%mutate_at("Cy3",~str_replace(.,'.*Challenged.*', 'infected')) %>% select(matches('cy')|matches('geo')) -> GSE51839
```

```{r}
##Single Channel , PBS and VHSV considerado infectado 
list_con_eset_filtrados$GSE56487 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite("Cy3",source_name_ch1,label_ch1) %>% mutate_at("Cy3",~str_replace(.,'.*empty plasmid-injected.*', 'control')) %>% mutate_at("Cy3",~str_replace(.,'.*VHSV.*', 'infected')) %>% select(matches('geo')|matches('cy')) -> GSE56487

```

```{r}
##P.salmonis
list_con_eset_filtrados$GSE43255 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite("Cy3", source_name_ch1) %>%unite("Cy5", source_name_ch2) %>% mutate_at("Cy3",~str_replace(.,'.*challenged.*', 'infected')) %>% mutate_at("Cy5",~str_replace(.,'.*control.*', 'control')) %>% select(matches('geo')|matches('cy'))->GSE43255
```

```{r}
#single channel
list_con_eset_filtrados$GSE45163 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>%  unite("Cy3",source_name_ch1,label_ch1) %>% mutate_at("Cy3",~str_replace(.,'.*(?i)control.*', 'control')) %>% mutate_at("Cy3",~str_replace(.,'.*infection.*', 'infected')) %>% select(matches('geo')|matches('cy')) -> GSE45163
```

```{r}
##Single channel, infecciones por organo 
list_con_eset_filtrados$GSE58823 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>%  unite("Cy3",source_name_ch1,label_ch1) %>% mutate_at("Cy3",~str_replace(.,'.*mock.*', 'control')) %>% mutate_at("Cy3",~str_replace(.,'.*infected.*', 'infected')) %>% select(matches('geo')|matches('cy')) ->GSE58823
```

```{r}
##Dye swap, no hay informacion de los canales (considerare Cy3 canal 1 y Cy5 canal 2)
list_con_eset_filtrados$GSE87920 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite("Cy3",source_name_ch1,label_ch1) %>% mutate_at("Cy3",~str_replace(.,'.*mock.*', 'control')) %>% mutate_at("Cy3",~str_replace(.,'.*salmonicida.*', 'infected'))  %>% unite("Cy5", source_name_ch2,label_ch2) %>% mutate_at("Cy5",~str_replace(.,'.*mock.*', 'control')) %>% select(matches('geo')|matches('cy')) -> GSE87920
```

```{r}
##single channel
list_con_eset_filtrados$GSE101695 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')|matches('title')) %>% unite("Cy3",title,label_ch1) %>% mutate_at("Cy3",~str_replace(.,'.*(?i)control.*', 'control')) %>% mutate_at("Cy3",~str_replace(.,'.*LG.*', 'infected')) %>% select(matches('geo')| matches("cy")) -> GSE101695
```

```{r}
list_con_eset_filtrados$GSE140756 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')|matches('title')) %>% unite("Cy3",title,label_ch1) %>% mutate_at("Cy3",~str_replace(.,'.*(?i)control.*', 'control')) %>% mutate_at("Cy3",~str_replace(.,'.*LG.*', 'infected')) %>% select(matches('geo')|matches('cy'))->GSE140756
```

```{r}
list_con_eset_filtrados$GSE6105 -> un_estudio
un_estudio     %>% pData %>% dplyr::select(matches('source.*ch') | matches('geo')| matches('label'))-> para_targets_0


para_targets_0 %>% mutate_at('source_name_ch1', ~str_replace(.,'.*control.*','control'))%>% 
                   mutate_at('source_name_ch1', ~str_replace(.,'.*infection.*','infected')) %>%
                   mutate(Biotin = source_name_ch1) %>% select(matches("geo|bio")) -> GSE6105

```


```{r}
#Chequeo
chequear_GSMs <- function(df_target, df, fila){(df_target  %>% select(-geo_accession)  %>% as.matrix %>% .[fila,]) %in%
                                         (df         %>% select(-geo_accession)  %>% as.matrix  %>% .[fila,] ) %>% all -> OKs
 
                                           return(OKs)}


OKs <- as.logical()
for(i in 1:nrow(df_target)){
                         chequear_GSMs(df_target,df,fila=i) -> OKs[i]
                           }

OKs %>% all
df_target -> GSE18219
```

```{r}
### juntando los targets
llist(GSE1012,GSE1031,GSE6105,GSE6350,`GSE6924-GPL3976`,`GSE6924-GPL2899` ,GSE10272,GSE13994,GSE15328,GSE19049,GSE19630,GSE20310,GSE18219,GSE19646,GSE26984,`GSE28843-GPL10679`,`GSE28843-GPL10705`,GSE30426,GSE30426,GSE28357,GSE34745,GSE35184,GSE35448,GSE35633,GSE35804,GSE36072,GSE36332,GSE38763,GSE40733,GSE26651,GSE39274,GSE42263,`GSE42847-GPL14875`,`GSE42847-GPL15180`,`GSE44352-GPL14875`,`GSE44352-GPL15180` ,GSE47057,GSE51603,GSE51839,GSE56487,GSE43255,GSE45163,GSE58823,GSE101695,GSE140756, GSE87920) -> mis.targets

saveRDS(mis.targets, path)
mis.targets <- readRDS(path)


```

############################
## Alejandro:
```{r}
download.file("https://www.dropbox.com/s/0jgehongd9ebh0k/mis_target.rds", destfile = "mis_target.rds", method = "wget")
mis.targets <- readRDS("mis_target.rds")
```

## Alejandro:
```{r warning=TRUE}
get_my_GSM <- function(un_codigo_gsm){ purrr::map(un_codigo_gsm,
                                                  function(un_codigo_gsm){ try(
                                                    GEOquery::getGEOSuppFiles(un_codigo_gsm, makeDirectory = TRUE, baseDir =getwd(), fetch_files = T ) )%>% 
                                                      rownames}) %>% unlist}
purrr::map(mis.targets, purrr::pluck("geo_accession")) -> mi_lista_GSE_GSM
mis.targets %<>% enframe %>% unnest 
purrr::map(mi_lista_GSE_GSM,get_my_GSM) -> all_gsms
all_gsms %>% enframe %>% unnest %>% mutate(geo_accession = str_extract(value, 'GSM\\d+') ) -> all_gsms_final
inner_join(mis.targets,all_gsms_final, by=c("geo_accession") ) -> target_final
### En caso de tener los archivos en el directorio local
saveRDS(target_final, saving)
target_final <- readRDS(saving)

```


```{r warning=TRUE}
##Extracción de extensiones 
str_extract(target_final$value, "[.]([a-z])*[.]") %>% unique() -> Extensiones
Extensiones
#puede ser utilizado para automatizar este proceso
```

```{r}
#Declaración de listas vacias
archivos_tif <- list()
archivos_gpr <- list()
archivos_ftr <- list()
archivos_txt <- list()
archivos_xml <- list()
archivos_tsv <- list()
whole_files <- list()
gsms_ftr <- list()
gsms_txt <- list()
gsms_gpr <- list()
gsms_xml <- list()
gsms_tif <- list()
gsms_tsv <- list()
##Todos los listas de gsms también son innecesarias 
for (i in 1:length(target_final$value)){
  
  if (str_extract(target_final$value[i], "[.]([a-z])*[.]") == ".tif." ){
    
    archivos_tif <-append(archivos_tif,target_final$value[i])
     gsms_tif <- append(gsms_tif, str_extract(target_final$value[i], "GSM\\d+") )
     whole_files <- append(whole_files, archivos_tif)
    }
  else if (str_extract(target_final$value[i], "[.]([a-z])*[.]") == ".ftr." ){
    archivos_ftr <-append(archivos_ftr,target_final$value[i])
    gsms_ftr <- append(gsms_ftr, str_extract(target_final$value[i], "GSM\\d+") )
    whole_files <- append(whole_files, archivos_ftr)
  }
  else if (str_extract(target_final$value[i], "[.]([a-z])*[.]") == ".xml." ){
    archivos_xml <-append(archivos_xml,target_final$value[i])
    gsms_xml <- append(gsms_xml, str_extract(target_final$value[i], "GSM\\d+") )
    whole_files <- append(whole_files, archivos_xml)
  }
  else if (str_extract(target_final$value[i], "[.]([a-z])*[.]") == ".txt." ){
    archivos_txt <-append(archivos_txt,target_final$value[i])
    gsms_txt <- append(gsms_txt, str_extract(target_final$value[i], "GSM\\d+") )
    whole_files <- append(whole_files, archivos_txt)
  }
  else if (str_extract(target_final$value[i], "[.]([a-z])*[.]") == ".gpr." ) {
    archivos_gpr <-append(archivos_gpr,target_final$value[i])
    gsms_gpr <- append(gsms_gpr, str_extract(target_final$value[i], "GSM\\d+") )
    whole_files <- append(whole_files, archivos_gpr)
  }
  else if (str_extract(target_final$value[i], "[.]([a-z])*[.]") == ".tsv.") {
    archivos_tsv <-append(archivos_tsv,target_final$value[i])
    gsms_tsv<- append(gsms_tsv, str_extract(target_final$value[i], "GSM\\d+") )
    whole_files <- append(whole_files, archivos_tsv)
  }
  
}
archivos_tif %>%  unlist() -> archivos_tif
archivos_gpr  %>% unlist() -> archivos_gpr
archivos_ftr  %>% unlist()  -> archivos_ftr
archivos_txt  %>% unlist()  -> archivos_txt
archivos_xml  %>% unlist()  -> archivos_xml
archivos_tsv  %>% unlist()  -> archivos_tsv
whole_files %>% unlist() %>% unique() -> whole_files


#esto también es innecesario
gsms_ftr %>%  unlist() %>% unique()-> gsms_ftr
gsms_txt %>%  unlist() %>% unique() -> gsms_txt
gsms_gpr %>%  unlist() %>% unique() -> gsms_gpr
gsms_tif %>%  unlist() %>% unique() -> gsms_tif
gsms_xml %>%  unlist() %>% unique() -> gsms_xml
gsms_tsv%>%  unlist() %>% unique() -> gsms_tsv
```

```{r}
unpack <- function(path){
  gunzip(path, remove = F, overwrite = T)
 }
test <- Vectorize(unpack)
test(target_final$value)
```

```{r}
extracted_gpr <- gsub('.gz', '',archivos_gpr) %>% unique()
parsing_from_match_to_end <- function(file_path){
  as.data.frame( fread(file = file_path,sep = '\t', skip = 'Block')) -> out
  return(out)
}
baptism <- function(path){
  id <-str_extract(path, 'GSM\\d+')
  return(id)
  
}
z<- extracted_gpr %>% map_chr(~baptism(.))
my.gpr.DFs <-map(extracted_gpr, parsing_from_match_to_end)
names(my.gpr.DFs) <- z
FileName <- list()

for(i in 1:length(names(my.gpr.DFs))){
  a.data.study <- my.gpr.DFs[[i]]
  old.names <- a.data.study %>%
    names() %>%
    str_extract_all("(^F[0-9]{3}.*Mean$)|(^B[0-9]{3}.*Mean$)|(^F[0-9]{3}+.*Median$)|(^B[0-9]{3}.*Median$)") %>%
    unlist()
  my.cols.new.names <- a.data.study %>%
    names() %>%
    str_extract_all("(^F[0-9]{3}.*Mean$)|(^B[0-9]{3}.*Mean$)|(^F[0-9]{3}+.*Median$)|(^B[0-9]{3}.*Median$)") %>%
    unlist() %>%
    str_replace_all('[:whitespace:]|(Rgn.*R.*)|\\.', '')
  my.gpr.DFs[[i]] %>%
    setnames(., old = old.names, new = my.cols.new.names)
  DF_ok <- my.gpr.DFs[[i]]
  
  names(my.gpr.DFs)[i] -> mi_gsm_en_la_iteracion
  
  str_extract(extracted_gpr, paste0(".*", mi_gsm_en_la_iteracion, ".*")) %>% 
    na.omit() %>% as.character() -> mi_ruta_al_gpr_en_la_iteracion
  
  str_replace(mi_ruta_al_gpr_en_la_iteracion,  "\\.gpr", "_Corrected.gpr") -> new.FileName.path
  for (j in 1:length(new.FileName.path)){
    write_delim(DF_ok, path= new.FileName.path[j], delim = "\t", na = "NA", append = FALSE)
    FileName <- append(FileName,new.FileName.path)  
  }
  
  
}
```


```{r}
names(my.gpr.DFs)
FileName<- FileName %>% unique()
FileName %>% str_extract('GSM\\d+') -> sample.names
sample.names_files <- cbind(row.names = sample.names,FileName)
target_final %>% filter(str_detect(value, '[.](gpr)*[.]')) ->target.ok
target.ok$value <- FileName %>% unlist()
colnames(target.ok)[11] <- c("FileName")
### la idea de esta función es distribuir los nombres de manera correcta.
```
red: 633 (o 6\\d\\d)
green: 543 (o 5\\d\\d)
F: forward
B: background
________________________________________________________________________
en .gpr                 en .txt  
un tipo de col:       otro tipo de col:
(^F6\\d\\d.*Mean$)     = ^rMeanSignal$       -> forward red mean
(^F5\\d\\d.*Mean$)     = ^gMeanSignal$       -> forward green mean
(^B6\\d\\d.*Median$)   = ^rBGMedianSignal$   -> background red median
(^B5\\d\\d.*Median$)   = ^gBGMedianSignal$   -> background green median
## 

```{r}
Volcano_generator <- function(adataframe){
  length(adataframe) -> limite
  z = 1
  while (z <= limite){
  adataframe[[z]] %>% names() %>% str_extract_all("(^F[0-9]{3}.*Mean$)|(^B[0-9]{3}.*Mean$)|(^F[0-9]{3}+.*Median$)|(^B[0-9]{3}.*Median$)") %>% unlist() -> real.names
 
   for (i in 1:length(real.names)) {
      
      if(real.names[i] == "F670Mean"| real.names[i] =="F635Mean"| real.names[i] =="F633Mean"){
        real.names[i] -> rojo_forward
      
    }
      else if (real.names[i] == "F532Mean"| real.names[i] =="F543Mean"|real.names[i] =="F570Mean") {
        real.names[i] -> verde_forward
      
    }
    
      else if(real.names[i]== "B670Median" |real.names[i] =="B633Median"|real.names[i] =="B635Median") {
        real.names[i] -> rojo_background
      }
    
      else if (real.names[i] == "B532Median"|real.names[i] =="B543Median"|real.names[i] =="B570Median") {
      real.names[i] -> verde_background
    }
        }
    RG          <- read.maimages(target.ok$FileName[z] ,source = "generic", columns = list(R= rojo_forward ,G= verde_forward,Rb=rojo_background ,Gb=verde_background), annotation = c("ProbeName", "SequenceID"))
    RG.bc2      <-backgroundCorrect(RG,method="normexp")
    RG.bc2.norm <- normalizeWithinArrays(RG.bc2, method="loess", weights = NULL)
    fit.1  <- lmFit(RG.bc2.norm,  design %>% as.matrix())
    fit2.1 <- eBayes(fit.1)
    diffexp            <- topTable(fit2.1, coef = colnames(design),confint = T, adjust.method="BH",sort.by = 'p', number=Inf)
    diffexp            <- data.frame(ID = diffexp[,1], log2FC = diffexp$logFC, adj.P.Val = diffexp$adj.P.Val,  CI.L = diffexp$CI.L, CI.R = diffexp$CI.R)
    output <- EnhancedVolcano(diffexp,
                lab = diffexp$ID,
                selectLab = NULL,
                x = 'log2FC',
                y = 'adj.P.Val',
                xlim = c(-6,6),
                xlab = bquote(~Log[2]~ 'fold change'),
                pCutoff = 0.01,
                FCcutoff = 1.0,
                pointSize = 1.0,
                labSize = 3.0,
                colAlpha = 1,
                legendPosition = 'right',
                legendLabSize = 12,
                legendIconSize = 4.0,
                drawConnectors = F,
                widthConnectors = 0.2,
                colConnectors = 'grey30',
                title = '',
                subtitle = '',
                ylim = c(0, 6))
    z = z+1
    }  
  return(output)
}
test <- my.gpr.DFs[[3]]
length(test)
Volcano_generator(my.gpr.DFs)
```


```{r}
RG          <- read.maimages(target.ok ,source = "generic", columns = list(R="F633Mean" ,G="F543Mean",Rb="B633Median",Gb="B543Median"), annotation = c("ProbeName", "SequenceID"))
RG.bc2      <-backgroundCorrect(RG,method="normexp")
RG.bc2.norm <- normalizeWithinArrays(RG.bc2, method="loess", weights = NULL)
modelMatrix(target.ok, ref = 'control') -> design

fit.1  <- lmFit(RG.bc2.norm,  design %>% as.matrix())

fit2.1 <- eBayes(fit.1)
diffexp            <- topTable(fit2.1, coef = colnames(design),confint = T, adjust.method="BH",sort.by = 'p', number=Inf)
diffexp            <- data.frame(ID = diffexp[,1], log2FC = diffexp$logFC, adj.P.Val = diffexp$adj.P.Val,  CI.L = diffexp$CI.L, CI.R = diffexp$CI.R)

EnhancedVolcano(diffexp,
                lab = diffexp$ID,
                selectLab = NULL,
                x = 'log2FC',
                y = 'adj.P.Val',
                xlim = c(-6,6),
                xlab = bquote(~Log[2]~ 'fold change'),
                pCutoff = 0.01,
                FCcutoff = 1.0,
                pointSize = 1.0,
                labSize = 3.0,
                colAlpha = 1,
                legendPosition = 'right',
                legendLabSize = 12,
                legendIconSize = 4.0,
                drawConnectors = F,
                widthConnectors = 0.2,
                colConnectors = 'grey30',
                title = '',
                subtitle = '',
                ylim = c(0, 6))
```







