---
title: "GSE1031"
output: html_notebook
---


```{r}
library("GEOquery")
library("tidyverse")
```

```{r}
e.set <-getGEO("GSE1031", AnnotGPL = TRUE, getGPL = TRUE)[[1]]
 ### GPL966 
getGEOfile("GSE1031", destdir = getwd())
Soft <- getGEO(filename ="/home/alejandro/Documentos/Meta_analisis_teleosteos/Test GSE1031/GSE1031.soft.gz")
Soft %>% str()
asd <- getGEO("GSE1031")
GSM16389<-Soft@gsms$GSM16389@dataTable@table
GSM16101<-Soft@gsms$GSM16101@dataTable@table
GSM16390<-Soft@gsms$GSM16390@dataTable@table
GSM16391<-Soft@gsms$GSM16391@dataTable@table
Soft@gsms$GSM16391@dataTable@table %>% colnames()
```


```{r}
GSM16389_final<- GSM16389 %>% select(c("CH1_MEAN", "CH1 Background Median", "CH2 Background Median", "CH2_MEAN", "ID_REF")) 
GSM16101_final<- GSM16101%>% select(c("CH1_MEAN", "CH1 Background Median", "CH2 Background Median", "CH2_MEAN", "ID_REF")) 
GSM16390_final<- GSM16390 %>% select(c("CH1_MEAN", "CH1 Background Median", "CH2 Background Median", "CH2_MEAN", "ID_REF")) 
GSM16391_final <-GSM16391 %>% select(c("CH1_MEAN", "CH1 Background Median", "CH2 Background Median", "CH2_MEAN", "ID_REF")) 
names(GSM16101_final) <-c( "verde_forward", "verde_background", "rojo_background","rojo_forward", "ID")
names(GSM16389_final) <-c( "verde_forward", "verde_background", "rojo_background","rojo_forward", "ID")
names(GSM16390_final) <-c( "verde_forward", "verde_background", "rojo_background","rojo_forward", "ID")
names(GSM16391_final) <-c( "verde_forward", "verde_background", "rojo_background","rojo_forward", "ID")

annotations<- e.set@featureData@data %>% select(matches("UniGene.ID|^ID$|GenBank.Accession"))
GSM16101_final <- merge(GSM16101_final, annotations)
GSM16389_final <- merge(GSM16389_final, annotations)
GSM16390_final <- merge(GSM16390_final, annotations)
GSM16391_final <- merge(GSM16391_final, annotations)
FileName <- c("/home/alejandro/Documentos/Meta_analisis_teleosteos/Test GSE1031/GSM16101.txt","/home/alejandro/Documentos/Meta_analisis_teleosteos/Test GSE1031/GSM16389.txt","/home/alejandro/Documentos/Meta_analisis_teleosteos/Test GSE1031/GSM16390.txt","/home/alejandro/Documentos/Meta_analisis_teleosteos/Test GSE1031/GSM16391.txt")
#### el objeto "target_final" se encuentra en el archivo rmd P.salmonis.rmd, y contiene los GSEs incluidos en el analisis

target_ok_rise <-data.frame( Cy3 = GSE1031$Cy3 ,Cy5 = GSE1031$Cy5, geo_accession = GSE1031$geo_accession, FileName)
write_delim(GSM16101_final, path="/home/alejandro/Documentos/Meta_analisis_teleosteos/Test GSE1031/GSM16101.txt", delim = "\t", na = "NA", append = FALSE)
write_delim(GSM16389_final, path="/home/alejandro/Documentos/Meta_analisis_teleosteos/Test GSE1031/GSM16389.txt", delim = "\t", na = "NA", append = FALSE)
write_delim(GSM16390_final, path="/home/alejandro/Documentos/Meta_analisis_teleosteos/Test GSE1031/GSM16390.txt", delim = "\t", na = "NA", append = FALSE)
write_delim(GSM16391_final, path="/home/alejandro/Documentos/Meta_analisis_teleosteos/Test GSE1031/GSM16391.txt", delim = "\t", na = "NA", append = FALSE)

```

```{r}
RG_rise         <- read.maimages(target_ok_rise ,source = "generic", columns = list(R= "rojo_forward" ,G= "verde_forward",Rb="rojo_background" ,Gb="verde_background"), annotation = c("UniGene ID", "ID", "GenBank Accession")) ### Dejar 3 anotaciones, "nombre de algo" sonda o gen y el ID.
    RG.bc2_rise      <-backgroundCorrect(RG_rise,method="subtract")
    RG.bc2.norm_rise <- normalizeWithinArrays(RG.bc2_rise, method="loess", weights = NULL, offset = 50)
    modelMatrix(target_ok_rise, ref = 'control') -> design_rise
    fit.1_rise  <- lmFit(RG.bc2.norm_rise,  design_rise %>% as.matrix())
    fit2.1_rise <- eBayes(fit.1_rise)
    diffexp_rise            <- topTable(fit2.1_rise, coef = colnames(design),confint = T, adjust.method="BH",sort.by = 'p', number=Inf)
    write_csv(diffexp_rise, file ="/home/alejandro/Documentos/Meta_analisis_teleosteos/Resultados_csv/diff_exp_Rise.csv")
    significativos <- diffexp_rise %>% filter(adj.P.Val < 0.05)
    colnames(diffexp_rise)[3]<-c('Name')
    summary(diffexp_rise)

```

```{r}
t_rise <- diffexp_rise$adj.P.Val
data.rise <- diffexp_rise[!duplicated(diffexp_rise$Name),]
data.rise <- data.rise[1: sum(t_rise < 0.05), ]
data.left.upregulated <- read.xlsx('/home/alejandro/Documentos/Meta_analisis_teleosteos/Meta_analisis/Rise-upregulated.xlsx',1)
data.left.downregulated <- read.xlsx('/home/alejandro/Documentos/Meta_analisis_teleosteos/Meta_analisis/Rise-down-regulated.xlsx',1)
colnames(data.left.upregulated)[1] <- c('Name')
colnames(data.left.downregulated)[1] <- c('Name')
join.upregulated <- inner_join(data.rise, data.left.upregulated, by = 'Name')
join.downregulated <- inner_join(data.rise, data.left.downregulated, by = 'Name')
dim(data.rise)
dim(data.left.upregulated)
dim(data.left.downregulated)
dim(join.upregulated)
dim(join.downregulated)
# abs diff between log fold change, en este caso esto no sera util puesto que los autores reportan solamente el mean fold change 
#abs.diff.HS <- abs(join.upregulated$logFC - data.left.upregulated$logFC)
#abs.diff.LS <- abs(join.downregulated$logFC - data.left.downregulated$)
#diferencias_valor_absoluto <- data.frame(diferencia = abs.diff.HS, Names = join.HS$Name)
#plot(abs.diff.HS)
#mean(abs.diff.LS)
#sd(abs.diff.LS)
```


```{r}
EnhancedVolcano(data.rise,
    lab = data.rise$UniGene.ID,
    selectLab = NULL,
    x = 'logFC',
    y = 'adj.P.Val',
    xlim = c(-3,3),
    xlab = bquote(~Log[2]~ 'fold change'),
    pCutoff = 0.05,
    FCcutoff = 1.0,
    pointSize = 0.8,
    labSize = 3.0,
    colAlpha = 1,
    legendPosition = 'right',
    legendLabSize = 12,
    legendIconSize = 4.0,
    drawConnectors = F,
    widthConnectors = 0.2,
    colConnectors = 'grey30',
    title = 'Volcano Plot diffe Rise',
    subtitle = 'for visual comparison',
    ylim = c(0,3)) 
```



