---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
setwd("~/RTesis/Tesis")
library(GEOquery)
my.gse.data <- getGEO('GSE42491',GSEMatrix = TRUE, AnnotGPL = TRUE, getGPL = TRUE)
saveRDS(my.gse.data, "GSE42491.rds")
```

```{r message=FALSE, warning=FALSE}
library(Biobase)
library(BiocGenerics)
setwd("~/RTesis/Tesis")
my.gse.data <- readRDS("GSE42491.rds")
my.gse.data
```


```{r message=FALSE, warning=FALSE}
library(GEOquery)
library(Biobase)
library(magrittr)
library(tidyr)
library(dplyr)

my.gse.data[[1]] %>% fData()  # para ver que selccionar, como esta escrito
my.gse.data[[1]] %>% fData() %>% select('NAME','SEQUENCE')          -> name.sequence
my.gse.data[[1]] %>% pData() %>% select(starts_with('label_ch'))  -> channels.labels

my.gse.data[[1]] %>% pData() %>% select(starts_with('source_name')) 
```


```{r message=FALSE, warning=FALSE}
library(stringr)

my.folder.raw      <- list.files(path=getwd(), recursive = F, pattern = "^GSE42491.*RAW$", full.names = T)

all.raw.files      <- list.files(path=my.folder.raw, recursive = F, full.names = T)
all.raw.files      <- all.raw.files[str_detect(all.raw.files,'.*txt$', negate = F)]
all.raw.files      <- all.raw.files[str_detect(all.raw.files, '.*JV.*', negate = T)]
study              <- unlist(str_extract_all(my.folder.raw, 'GS[aA-zZ]+\\d+.*'))
all.raw.files
```
GSM1040892_US83800208_253652710005_S01_GE2-v5_10_Apr08_2_1.txt"
GSM1040893_US83800208_253652710005_S01_GE2-v5_10_Apr08_2_2.txt"
GSM1040894_US83800208_253652710005_S01_GE2-v5_10_Apr08_2_3.txt"
GSM1040895_US83800208_253652710006_S01_GE2-v5_10_Apr08_1_3.txt"
GSM1040896_US83800208_253652710006_S01_GE2-v5_10_Apr08_1_4.txt"
GSM1040897_US83800208_253652710006_S01_GE2-v5_10_Apr08_2_1.txt"
GSM1040898_US83800208_253652710006_S01_GE2-v5_10_Apr08_2_2.txt"
GSM1040899_US83800208_253652710006_S01_GE2-v5_10_Apr08_2_3.txt"
GSM1040900_US83800208_253652710006_S01_GE2-v5_10_Apr08_2_4.txt"

```{r}
library(limma)

my.rownames <- rownames(channels.labels)

Cy3 <- rep('control',length(my.rownames))
Cy5 <- rep('infected',length(my.rownames))

data.frame(Cy3,Cy5)  %>% trqwe::set_rownames(my.rownames) -> my.target_Cy3_Cy5

modelMatrix(my.target_Cy3_Cy5, ref = 'control') -> design
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
all.raw.data.files <- list()$data.frame
for(j in 1:length(all.raw.files)){
                                  line <- 0L
                                 input <- "start"
                                while( !str_detect(input, '.*FEATURES.*')) {
                                line <- line + 1L
                                input <-  read_lines(file = all.raw.files[j], skip = line - 1L, n_max = 1L )
                                }
                                  all.raw.data.files[[study]]$data[[unlist(str_extract_all(all.raw.files[j], 'GSM\\d+.*'))]] <- 
                                  as.data.frame(read_delim(all.raw.files[j], delim= "\t",  skip = line-1))
}
#str(all.raw.data.files) #para chequear
all.raw.data.files[[1]]$data[[1]] %>% names() 
```

           
                     
"gMeanSignal"
"rMeanSignal"                   
"gMedianSignal"
"rMedianSignal"                    

```{r message=FALSE, warning=FALSE}
for(i in 1:length(names(all.raw.data.files[[study]]$data))){
  
                                            a.data.study       <- all.raw.data.files[[study]]$data[[i]]
                                            #my.cols.bool       <- a.data.study %>% names() %>% str_detect("(F6\\d\\d.*Mean$)|(F5\\d\\d.*Mean$)|(B6\\d\\d.*Median$)|(B5\\d\\d.*Median$)") 
                                            #my.cols.init.names <- names(a.data.study)[my.cols.bool]
                                            #my.cols.init.names%>% str_replace_all('.(?=(Median|Mean))','.')  -> my.cols.names.ok
                                            
                                            
                                            #names(a.data.study)[my.cols.bool] <- my.cols.names.ok
                                            all.raw.data.files[[study]]$data %>% names() %>% .[i] -> FileName
                                            my.file.path <- all.raw.files[str_detect(all.raw.files, FileName)]
                                            my.file.path %>% str_extract('.*(?=(.txt))') %>% paste0('_JV.txt')  -> new.FileName.path
                                            write_delim(x=a.data.study, path= new.FileName.path, delim = "\t", na = "NA", append = FALSE)
}

```

```{r}
list.files(path=my.folder.raw, recursive = F, full.names = T) %>% str_extract_all('.*_JV.txt') %>% unlist() -> FileName
FileName %>% str_extract('GSM\\d+') -> sample.names

data.frame(FileName)  %>% trqwe::set_rownames(sample.names)                    -> sample.names_files
merge(my.target_Cy3_Cy5, sample.names_files, by=0) %>% column_to_rownames('Row.names') -> target.ok
```



Ver cuales muestras vamos a analizar:
```{r}
library(Biobase)
#my.gse.data[[1]] %>% pData() %>% filter(str_detect(title, regex("day.*15", ignore_case = TRUE))) 
my.gse.data[[1]] %>% pData() %>% select('title') %>% as.matrix()  %>% str_detect("^12h") %>% which() -> a.subset
a.subset
```
Buscar la columna con los IDs:
```{r}
a.data.study
```


```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(limma)

RG          <- read.maimages(target.ok[a.subset,], columns=list(R="rMeanSignal",G="gMeanSignal",Rb="rBGMedianSignal",Gb="gBGMedianSignal"), annotation = 'GeneName')
RG.bc2      <-backgroundCorrect(RG,method="normexp")
RG.bc2.norm <- normalizeWithinArrays(RG.bc2, method="loess", weights = NULL)
#En este caso la referencia son todos Cy3 (no-inf). Todos los inf son Cy5. Sin Dye-swap. Con dye-swap poner columna 'Dye', Cy3 control o referencia  (no-inf o ref-universal).
fit.1  <- lmFit(RG.bc2.norm, design[a.subset,] %>% as.matrix() %>% trqwe::set_colnames(colnames(design)))
fit2.1 <- eBayes(fit.1)
diffexp            <- topTable(fit2.1, coef = 'infected',confint = T, adjust.method="BH",sort.by = 'p', number=Inf)

diffexp            <- data.frame(ID = diffexp$GeneName, log2FC = diffexp$logFC, adj.P.Val = diffexp$adj.P.Val,  CI.L = diffexp$CI.L, CI.R = diffexp$CI.R)
diffexp
```

```{r fig.height=7, fig.width=15}
library(EnhancedVolcano)
EnhancedVolcano(diffexp,
    lab = diffexp$ID,
    selectLab = NULL,
    x = 'log2FC',
    y = 'adj.P.Val',
    xlim = c(-6,6),
    xlab = bquote(~Log[2]~ 'fold change'),
    pCutoff = 0.05,
    FCcutoff = 1.0,
    pointSize = 1.0,
    labSize = 3.0,
    colAlpha = 1,
    legendPosition = 'right',
    legendLabSize = 12,
    legendIconSize = 4.0,
    drawConnectors = F,
    widthConnectors = 0.2,
    colConnectors = 'grey30',
    title = '',
    subtitle = '',
    ylim = c(0, 6)) 

#Cambiar los cutoffs para todas las familias
```
#######################################################################################