---
title: "P.salmonis"
output: html_notebook
---
```{r}
library(easypackages)
librerias <- c("GEOquery","Biobase","BiocGenerics","magrittr","tidyr","dplyr","stringr","limma","EnhancedVolcano", "purrr","foreach","tidyverse", "xlsx","Hmisc", "tidyverse", "PAA", "data.table", "ArrayExpress", "SRAdb")
libraries(librerias)
```

```{r}
#Rutas de guardado y lectura
pth <- file.path(getwd(), "mis_gse_data_1.rds")
path <- file.path(getwd(), "mis_target.psalmonis.rds")
saving <- file.path(getwd(), "tabla_targets_p_salmonis.rds")
```

```{r}
titulos <- data.frame()
list_con_eset_filtrados <- list()
RDS <- readRDS(pth)
b <- RDS %>% names()
for (i in 1:length(b)) {
  if ( b[i] == "GSE1031") {
    RDS[[i]] -> mi.gse
    pData(mi.gse) %>%
      filter(str_detect(source_name_ch1, "(?i)Non-infected|Piscirickettsia") & str_detect(source_name_ch2, "(?i)Non-infected|(?i)Piscirickettsia")) %>%
      rownames() %>%
      mi.gse[, .] -> un_eset_filtrado
  }
  else if (b[i] == "GSE43255") {
    RDS[[i]] -> mi.gse
    pData(mi.gse) %>%
      filter(str_detect(title, "High")) %>%
      rownames() %>%
      mi.gse[, .] -> un_eset_filtrado
  }
  titulos <- bind_rows(titulos, pData(un_eset_filtrado))

  list_con_eset_filtrados[[b[i]]] <- un_eset_filtrado
}
list_con_eset_filtrados %>%
  map(pData) %>%
  enframe() %>%
  unnest() %>%
  dplyr::select(matches("^name$|title|geo|source|characteristics|organism")) -> GSMs_filtrados
```

```{r}
list_con_eset_filtrados$GSE1031 -> un_estudio 
un_estudio %>% pData %>% select(matches('geo')| matches('source.*ch')) %>% unite("Cy3",source_name_ch1) %>%unite("Cy5",source_name_ch2) %>%  mutate_at('Cy3', ~str_replace(.,'.*Non-infected.*', 'control')) %>% mutate_at('Cy3', ~str_replace(.,'.*salmonis-infected.*', 'infected')) %>% mutate_at('Cy5', ~str_replace(.,'.*Non-infected.*', 'control')) %>% mutate_at('Cy5', ~str_replace(.,'.*salmonis-infected.*', 'infected')) %>% select(matches('geo')|matches('cy')) -> GSE1031 

list_con_eset_filtrados$GSE1012 -> un_estudio 
un_estudio %>% pData %>% select(matches('geo')| matches('source.*ch')) %>% unite("Cy3",source_name_ch1) %>%unite("Cy5",source_name_ch2) %>%  mutate_at('Cy3', ~str_replace(.,'(?i).*Non-infected.*', 'control')) %>% mutate_at('Cy3', ~str_replace(.,'.*salmonis-infected.*', 'infected')) %>% mutate_at('Cy5', ~str_replace(.,'(?i).*Non-infected.*', 'control')) %>% mutate_at('Cy5', ~str_replace(.,'.*salmonis-infected.*', 'infected')) -> GSE1012

list_con_eset_filtrados$GSE43255 -> un_estudio 
un_estudio %>% pData %>% select(matches('source_name_ch*') | matches('geo')| matches('label')) %>% unite("Cy3", source_name_ch1) %>%unite("Cy5", source_name_ch2) %>% mutate_at("Cy3",~str_replace(.,'.*challenged.*', 'infected')) %>% mutate_at("Cy5",~str_replace(.,'.*control.*', 'control')) %>% select(matches('geo')|matches('cy'))->GSE43255
```



```{r}
## estudios que tienen match con Salmo salar
RDS$GSE1012 %>% pData() #p. salmonis Atlantic Salmon macrofagos infectados
RDS$GSE1031 %>% pData() #p. salmonis Atlantic Salmon 
RDS$GSE43255%>% pData() %>% select(matches("organism_ch*")) # p. salmonis, PAPER PROFE




### podria ser utilizados para enrobustecer el grupo Control
RDS$GSE19630 %>% pData() %>% select(matches("organism_ch*")) #Anemia virus ISAV
RDS$GSE26984 %>% pData() %>% select(matches("organism_ch*")) # challenged with l. salmonis
RDS$`GSE28843-GPL10679` %>% pData() %>% select(matches("organism_ch*")) # piscine myocarditis virus
RDS$`GSE28843-GPL10705` %>% pData() %>% select(matches("organism_ch*"))#  piscine myocarditis virus
RDS$GSE28357 %>% pData() %>% select(matches("organism_ch*")) # Isav exposure
RDS$GSE36072%>% pData() %>% select(matches("organism_ch*")) #parasitic copepod Lepeophtheirus salmonis
RDS$GSE36332%>% pData() %>% select(matches("organism_ch*"))# Y. ruckeri
RDS$GSE101695%>% pData() %>% select(matches("organism_ch*")) #Salmo trutta L. garvieae-infected
RDS$GSE140756%>% pData() %>% select(matches("organism_ch*")) #Chalimus 

```

```{r}
llist(GSE1031,GSE43255) -> mis.targets

saveRDS(mis.targets, path)
mis.targets <- readRDS(path)
```

```{r}
## En caso de no tener los archivos gsms en el directorio local
get_my_GSM <- function(un_codigo_gsm){ purrr::map(un_codigo_gsm,
                                                  function(un_codigo_gsm){ try(
                                                    GEOquery::getGEOSuppFiles(un_codigo_gsm, makeDirectory = TRUE, baseDir =getwd(), fetch_files = T ) )%>% 
                                                      rownames}) %>% unlist}
purrr::map(mis.targets, purrr::pluck("geo_accession")) -> mi_lista_GSE_GSM
mis.targets %<>% enframe %>% unnest 
purrr::map(mi_lista_GSE_GSM,get_my_GSM) -> all_gsms
all_gsms %>% enframe %>% unnest %>% mutate(geo_accession = str_extract(value, 'GSM\\d+') ) -> all_gsms_final
inner_join(mis.targets,all_gsms_final, by=c("geo_accession") ) -> target_final
### En caso de tener los archivos en el directorio local
saveRDS(target_final, saving)
target_final <- readRDS(saving)
#full_join(mis.targets,hola2, by=c("geo_accession") ) -> target_final2
#identical(target_final$name.x, target_final$name.y) # just a check

```

```{r}
##Comparador para descompresiones ordenadas

str_extract(target_final$value, "[.]([a-z])*[.]") %>% unique() -> Extensiones
all_extensions <- c(".tif.",".gpr.",".ftr.",".txt." ,".xml.", ".tsv." )

```

```{r}
#Declaración de listas vacias
archivos_tif <- list()
archivos_gpr <- list()
archivos_ftr <- list()
archivos_txt <- list()
archivos_xml <- list()
archivos_tsv <- list()

##Todos los listas de gsms también son innecesarias 
for (i in 1:length(target_final$value)){
  
  if (str_extract(target_final$value[i], "[.]([a-z])*[.]") == ".tif." ){
    
    archivos_tif <-append(archivos_tif,target_final$value[i])
     
    }
  else if (str_extract(target_final$value[i], "[.]([a-z])*[.]") == ".ftr." ){
    archivos_ftr <-append(archivos_ftr,target_final$value[i])
    
  }
  else if (str_extract(target_final$value[i], "[.]([a-z])*[.]") == ".xml." ){
    archivos_xml <-append(archivos_xml,target_final$value[i])

  }
  else if (str_extract(target_final$value[i], "[.]([a-z])*[.]") == ".txt." ){
    archivos_txt <-append(archivos_txt,target_final$value[i])
    
  }
  else if (str_extract(target_final$value[i], "[.]([a-z])*[.]") == ".gpr." ) {
    archivos_gpr <-append(archivos_gpr,target_final$value[i])
  
  }
  else if (str_extract(target_final$value[i], "[.]([a-z])*[.]") == ".tsv.") {
    archivos_tsv <-append(archivos_tsv,target_final$value[i])
    
  }
  
}
archivos_tif %>%  unlist() -> archivos_tif
archivos_gpr  %>% unlist() -> archivos_gpr
archivos_ftr  %>% unlist()  -> archivos_ftr
archivos_txt  %>% unlist()  -> archivos_txt
archivos_xml  %>% unlist()  -> archivos_xml
archivos_tsv  %>% unlist()  -> archivos_tsv
```


```{r}
unpack <- function(path){
  gunzip(path, remove = F, overwrite = T)
 }
test <- Vectorize(unpack)
test(target_final$value)
```

```{r}
### for GPR files

extracted_gpr <- gsub('.gz', '',archivos_gpr) %>% unique()

parsing_from_match_to_end <- function(file_path){
  as.data.frame(fread(file = file_path,sep = '\t', skip = 'Block')) -> out
  return(out)
}
baptism <- function(path){
  id <-str_extract(path, 'GSM\\d+')
  return(id)
  
}
z<- extracted_gpr %>% map_chr(~baptism(.))
my.gpr.DFs <-map(extracted_gpr, parsing_from_match_to_end)
names(my.gpr.DFs) <- z
FileName <- list()

for(i in 1:length(names(my.gpr.DFs))){
  a.data.study <- my.gpr.DFs[[i]]
  transform <- a.data.study %>%
    names() %>%
    str_extract_all("(^F[0-9]{3}.*Mean$)|(^B[0-9]{3}.*Median$)") %>%
    unlist()
  old.names <- a.data.study %>%
    names() %>%
    str_extract_all("(^F[0-9]{3}.*Mean$)|(^B[0-9]{3}.*Median$)") %>%
    unlist()
  
  for (j in 1:length(old.names)) {
      
      if(str_detect(old.names[j],"^F6[0-9]{2}.*Mean$")){
        old.names[j] <- "rojo_forward"
      
    }
      else if (str_detect(old.names[j],"^F5[0-9]{2}.*Mean$")) {
        old.names[j] <- "verde_forward"
      
    }
    
      else if(str_detect(old.names[j],"^B6[0-9]{2}.*Median$") ) {
        old.names[j] <- "rojo_background"
      }
    
      else if (str_detect(old.names[j],"^B5[0-9]{2}.*Median$")) {
      old.names[j] <- "verde_background"
      }
   
  }
  
  my.cols.new.names <- old.names %>% 
    unlist() 
    my.gpr.DFs[[i]] %>%
    setnames(., old = transform, new = my.cols.new.names, skip_absent=TRUE)
  DF_ok <- my.gpr.DFs[[i]]
  
  names(my.gpr.DFs)[i] -> mi_gsm_en_la_iteracion
  
  str_extract(extracted_gpr, paste0(".*", mi_gsm_en_la_iteracion, ".*")) %>% 
    na.omit() %>% as.character() -> mi_ruta_al_gpr_en_la_iteracion
  
  str_replace(mi_ruta_al_gpr_en_la_iteracion,  "\\.gpr", "_Corrected.gpr") -> new.FileName.path
  for (j in 1:length(new.FileName.path)){
    write_delim(DF_ok, path= new.FileName.path[j], delim = "\t", na = "NA", append = FALSE)
    FileName <- append(FileName,new.FileName.path)  
  }
  
  
}
FileName<- FileName %>% unique()
FileName %>% str_extract('GSM\\d+') -> sample.names
sample.names_files <- cbind(row.names = sample.names,FileName)
target_final %>% filter(str_detect(value, '[.](gpr)*[.]')) ->target.ok
target.ok$value <- FileName %>% unlist()
colnames(target.ok)[6] <- c("FileName")
```
Blast contra los GPL.
```{r}
RG          <- read.maimages(target.ok$FileName ,source = "generic", columns = list(R= "rojo_forward" ,G= "verde_forward",Rb="rojo_background" ,Gb="verde_background"), annotation = c("Name", "ID")) ### Dejar 3 anotaciones, "nombre de algo" sonda o gen y el ID.
    RG.bc2      <-backgroundCorrect(RG,method="normexp")
    RG.bc2.norm <- normalizeWithinArrays(RG.bc2, method="loess", weights = NULL)
    modelMatrix(target.ok, ref = 'control') -> design
    fit.1  <- lmFit(RG.bc2.norm,  design %>% as.matrix())
    fit2.1 <- eBayes(fit.1)
    diffexp            <- topTable(fit2.1, coef = colnames(design),confint = T, adjust.method="BH",sort.by = 'p', number=Inf)
```


```{r}
 #diffexp            <- data.frame(ID = diffexp[,1], log2FC = diffexp$logFC, adj.P.Val = diffexp$adj.P.Val,  CI.L = diffexp$CI.L, CI.R = diffexp$CI.R)
EnhancedVolcano(diffexp,
                lab = diffexp$ID,
                selectLab = NULL,
                x = 'log2FC',
                y = 'adj.P.Val',
                xlim = c(-6,6),
                xlab = bquote(~Log[2]~ 'fold change'),
                pCutoff = 0.01,
                FCcutoff = 1.0,
                pointSize = 1.0,
                labSize = 3.0,
                colAlpha = 1,
                legendPosition = 'right',
                legendLabSize = 12,
                legendIconSize = 4.0,
                drawConnectors = F,
                widthConnectors = 0.2,
                colConnectors = 'grey30',
                title = '',
                subtitle = '',
                ylim = c(0, 6))

```

```{r}
### For array express 
#Cargar expressionset desde array express
load("~/Documentos/Meta_analisis_teleosteos/Meta_analisis/E-MTAB-685.eSet.r")
fdata_study<-fData(study)
assayDataElementNames(study)
red <- assayDataElement(study,"R") %>% as.data.frame()
red_back <- assayDataElement(study,"Rb") %>% as.data.frame()
green = assayDataElement(study,"G")%>% as.data.frame()
green_back <- assayDataElement(study,"Gb")%>% as.data.frame()

red1 <- red["10031 2 uncom tif_GE2-v5_95_Feb07_1_1"]
red_back1 <- red_back["10031 2 uncom tif_GE2-v5_95_Feb07_1_1"]
green1 = green["10031 2 uncom tif_GE2-v5_95_Feb07_1_1"]
green_back1 <- green_back["10031 2 uncom tif_GE2-v5_95_Feb07_1_1"]

red2 <-red["10031 2 uncom tif_GE2-v5_95_Feb07_1_2"]
red_back2 <- red_back["10031 2 uncom tif_GE2-v5_95_Feb07_1_2"]
green2 = green["10031 2 uncom tif_GE2-v5_95_Feb07_1_2"]
green_back2 <-  green_back["10031 2 uncom tif_GE2-v5_95_Feb07_1_2"]

red3 <- red["10031 2 uncom tif_GE2-v5_95_Feb07_1_3"]
red_back3 <- red_back["10031 2 uncom tif_GE2-v5_95_Feb07_1_3"]
green3 = green["10031 2 uncom tif_GE2-v5_95_Feb07_1_3"]
green_back3 <- green_back["10031 2 uncom tif_GE2-v5_95_Feb07_1_3"]

red4 <- red["10031 2 uncom tif_GE2-v5_95_Feb07_1_4"]
red_back4 <- red_back["10031 2 uncom tif_GE2-v5_95_Feb07_1_4"]
green4 = green["10031 2 uncom tif_GE2-v5_95_Feb07_1_4"]
green_back4 <-green_back["10031 2 uncom tif_GE2-v5_95_Feb07_1_4"] 


```


```{r}
Sequence_probs <- parsing_from_match_to_end("~/Documentos/Meta_analisis_teleosteos/Meta_analisis/A-MEXP-2065.adf.txt")
Sequence_probs$Row <-seq(1:length(Sequence_probs$Row))
Sequence_probs$Row %<>% as.character() 

v5_95_Feb07_1_1 <- as.data.frame(cbind(red1[,"10031 2 uncom tif_GE2-v5_95_Feb07_1_1"], red_back1[,"10031 2 uncom tif_GE2-v5_95_Feb07_1_1"], green1[, "10031 2 uncom tif_GE2-v5_95_Feb07_1_1"], green_back1[, "10031 2 uncom tif_GE2-v5_95_Feb07_1_1"]))
colnames(v5_95_Feb07_1_1) <- c("rojo_forward", "rojo_background", "verde_forward", "verde_background")
v5_95_Feb07_1_1_row <- v5_95_Feb07_1_1 %>% rownames_to_column("Row") %>%

v5_95_Feb07_1_2 <- as.data.frame(cbind(red2[,"10031 2 uncom tif_GE2-v5_95_Feb07_1_2"], red_back2[,"10031 2 uncom tif_GE2-v5_95_Feb07_1_2"], green2[, "10031 2 uncom tif_GE2-v5_95_Feb07_1_2"], green_back2[, "10031 2 uncom tif_GE2-v5_95_Feb07_1_2"]))
colnames(v5_95_Feb07_1_2) <- c("rojo_forward", "rojo_background", "verde_forward", "verde_background")
v5_95_Feb07_1_2_row <- v5_95_Feb07_1_2 %>% rownames_to_column("Row")

v5_95_Feb07_1_3 <- as.data.frame(cbind(red3[,"10031 2 uncom tif_GE2-v5_95_Feb07_1_3"], red_back3[,"10031 2 uncom tif_GE2-v5_95_Feb07_1_3"], green3[, "10031 2 uncom tif_GE2-v5_95_Feb07_1_3"], green_back3[, "10031 2 uncom tif_GE2-v5_95_Feb07_1_3"]))
colnames(v5_95_Feb07_1_3) <- c("rojo_forward", "rojo_background", "verde_forward", "verde_background")
v5_95_Feb07_1_3_row <- v5_95_Feb07_1_3 %>% rownames_to_column("Row")

v5_95_Feb07_1_4 <- as.data.frame(cbind(red4[,"10031 2 uncom tif_GE2-v5_95_Feb07_1_4"], red_back4[,"10031 2 uncom tif_GE2-v5_95_Feb07_1_4"], green4[, "10031 2 uncom tif_GE2-v5_95_Feb07_1_4"], green_back4[, "10031 2 uncom tif_GE2-v5_95_Feb07_1_4"]))
colnames(v5_95_Feb07_1_4) <- c("rojo_forward", "rojo_background", "verde_forward", "verde_background")
v5_95_Feb07_1_4_row <- v5_95_Feb07_1_4 %>% rownames_to_column("Row")
```

```{r}
v5_95_Feb07_1_1_row
v5_95_Feb07_1_2_row 
v5_95_Feb07_1_3_row 
v5_95_Feb07_1_4_row 
all_equal(v5_95_Feb07_1_4_row ,v5_95_Feb07_1_3_row )
identical(as.matrix(v5_95_Feb07_1_1_row), as.matrix(v5_95_Feb07_1_2_row))
identical(as.matrix(v5_95_Feb07_1_1_row), as.matrix(v5_95_Feb07_1_3_row))
identical(as.matrix(v5_95_Feb07_1_1_row), as.matrix(v5_95_Feb07_1_4_row))

identical(as.matrix(v5_95_Feb07_1_2_row), as.matrix(v5_95_Feb07_1_1_row))
identical(as.matrix(v5_95_Feb07_1_2_row), as.matrix(v5_95_Feb07_1_3_row))
identical(as.matrix(v5_95_Feb07_1_2_row), as.matrix(v5_95_Feb07_1_4_row))

identical(as.matrix(v5_95_Feb07_1_3_row), as.matrix(v5_95_Feb07_1_1_row))
identical(as.matrix(v5_95_Feb07_1_3_row), as.matrix(v5_95_Feb07_1_2_row))
identical(as.matrix(v5_95_Feb07_1_3_row), as.matrix(v5_95_Feb07_1_4_row))

identical(as.matrix(v5_95_Feb07_1_4_row), as.matrix(v5_95_Feb07_1_1_row))
identical(as.matrix(v5_95_Feb07_1_4_row), as.matrix(v5_95_Feb07_1_2_row))
identical(as.matrix(v5_95_Feb07_1_4_row), as.matrix(v5_95_Feb07_1_3_row))
```
```{r}
Sequence_probs$Row %>% length()
Sequence_probs$Row %>% unique() %>% length()
v5_95_Feb07_1_1_row$Row %>%  length()
v5_95_Feb07_1_1_row$Row %>%  unique() %>% length()
```

```{r}
test<- merge(v5_95_Feb07_1_1_row, Sequence_probs)
 write_delim(test, path= "~/Documentos/Meta_analisis_teleosteos/Meta_analisis/10031_2_uncom_tif_GE2-v5_95_Feb07_1_1_corrected.txt", delim = "\t", na = "NA", append = FALSE)
```



```{r}
test<- merge(v5_95_Feb07_1_1_row, Sequence_probs)
 write_delim(test, path= "~/Documentos/Meta_analisis_teleosteos/Meta_analisis/10031_2_uncom_tif_GE2-v5_95_Feb07_1_1_corrected.txt", delim = "\t", na = "NA", append = FALSE)
test2<-inner_join(v5_95_Feb07_1_2_row, Sequence_probs, by = "Row")
write_delim(test2, path= "~/Documentos/Meta_analisis_teleosteos/Meta_analisis/10031_2_uncom_tif_GE2-v5_95_Feb07_1_2_corrected.txt", delim = "\t", na = "NA", append = FALSE)
test3<-inner_join(v5_95_Feb07_1_3_row, Sequence_probs, by = "Row")
write_delim(test3, path= "~/Documentos/Meta_analisis_teleosteos/Meta_analisis/10031_2_uncom_tif_GE2-v5_95_Feb07_1_3_corrected.txt", delim = "\t", na = "NA", append = FALSE)
test4<-inner_join(v5_95_Feb07_1_4_row, Sequence_probs, by = "Row")
write_delim(test4, path= "~/Documentos/Meta_analisis_teleosteos/Meta_analisis/10031_2_uncom_tif_GE2-v5_95_Feb07_1_4_corrected.txt", delim = "\t", na = "NA", append = FALSE)


Accesion <- c("10031", "10031" , "10031" ,"10031")
Cy3 <- c("Control","Control","Control","Control")
Cy5 <- c("Infected", "Infected","Infected","Infected")
Filename <- c("~/Documentos/Meta_analisis_teleosteos/Meta_analisis/10031_2_uncom_tif_GE2-v5_95_Feb07_1_1_corrected.txt","~/Documentos/Meta_analisis_teleosteos/Meta_analisis/10031_2_uncom_tif_GE2-v5_95_Feb07_1_2_corrected.txt","~/Documentos/Meta_analisis_teleosteos/Meta_analisis/10031_2_uncom_tif_GE2-v5_95_Feb07_1_3_corrected.txt","~/Documentos/Meta_analisis_teleosteos/Meta_analisis/10031_2_uncom_tif_GE2-v5_95_Feb07_1_4_corrected.txt")
target_test <- data.frame(Cy3, Cy5, Accesion, Filename)
```

```{r}
read.delim(target_test$Filename[1])
read.delim(target_test$Filename[2])
read.delim(target_test$Filename[3])
read.delim(target_test$Filename[4])
```


```{r}
RG          <- read.maimages(target_test$Filename ,source = "generic", columns = list(R= "rojo_forward" ,G= "verde_forward",Rb="rojo_background" ,Gb="verde_background"), annotation = c("Reporter Name", "Reporter Sequence"))
study$Array.Data.File
RG.bc2      <-backgroundCorrect(RG,method="normexp")
    RG.bc2.norm <- normalizeWithinArrays(RG.bc2, method="none", weights = NULL)
    modelMatrix(target_test, ref = 'Control') -> design
    fit.1  <- lmFit(RG.bc2.norm,  design %>% as.matrix())
    fit2.1 <- eBayes(fit.1, robust = TRUE)
    diffexp            <- topTable(fit2.1, coef = colnames(design),confint = T, adjust.method="BH",sort.by = 'p', number=Inf)
    ?topTable
    ? lmFit
    ?eBayes
    ?normalizeWithinArrays
    
    diffexp 
```

```{r}

```


```{r}
## For tiff files
extracted_tif <- gsub('.gz', '',archivos_tif) %>% unique()
n<- extracted_tif %>% map_chr(~baptism(.))
coralRG <- read.maimages(extracted_tif)


```


```{r}
for(i in 1:length(archivos_ftr)){
                                  line      <- 0L
                                  input     <- 'string_inicial'
                                  a.file    <- archivos_ftr[i]
                                  sample.id <- str_extract(a.file, 'GSM\\d+')
                                  #leemos linea por linea hasta encontrar la regex 
                                  while(!str_detect(input, regex('^FEATURES|^block', ignore_case = T))){
                                       line  <- line + 1L
                                       input <- read_lines(a.file, skip = line - 1L, n_max = 1L)
                                       }
                                  
                                as.data.frame(read_delim(a.file, delim = '\t', skip = line-1)) -> my.ftr.DFs[[sample.id]]
                                  
}
```


```{r}
for(i in 1:length(archivos_tsv)){
                                  line      <- 0L
                                  input     <- 'string_inicial'
                                  a.file    <- archivos_tsv[i]
                                  sample.id <- str_extract(a.file, 'GSM\\d+')
                                  #leemos linea por linea hasta encontrar la regex 
                                  while(!str_detect(input, regex('^FEATURES|^block', ignore_case = T))){
                                       line  <- line + 1L
                                       input <- read_lines(a.file, skip = line - 1L, n_max = 1L)
                                       }
                                  
                                as.data.frame(read_delim(a.file, delim = '\t', skip = line-1)) -> my.tsv.DFs[[sample.id]]
                                  
}

```

```{r}
#chequeo que están las cuatro columnas que necesitamos
#Chequear que hayan exponenciales, subínides ni superíndices.
my.gpr.DFs[[1]] %>% colnames() %>% str_extract_all('^rMeanSignal$|^gMeanSignal$|^rBGMedianSignal$|^gBGMedianSignal$') %>% unlist()
```

```{r}
for(i in 1:length(names(my.txt.DFs))){
  
                                            a.data.study          <- my.txt.DFs[[i]]
                                            #
                                            my.cols.init.names    <- a.data.study %>% names() %>%
                                            str_extract_all("(^F[0-9]+.*Mean$)|(^B[0-9]+.*Mean$)|(Rgn.*R.*)|(r|g)MeanSignal$|(r|g)BGMedianSignal$") %>% unlist
                                            #
                                            my.cols.init.names %>% str_replace_all('[:whitespace:]|(Rgn.*R.*)', '')  -> my.cols.names.ok
                                            
                                            colnames(my.txt.DFs[[i]][, my.cols.init.names]) <- my.cols.names.ok
                                            DF_ok <- my.txt.DFs[[i]]
                                            
                                            names(my.txt.DFs)[i] -> mi_gsm_en_la_iteracion
                                            
                                            str_extract(archivos_txt, paste0(".*", mi_gsm_en_la_iteracion, ".*")) %>% 
                                              na.omit() %>% as.character() -> mi_ruta_al_txt_en_la_iteracion
                                            
                                            str_replace(mi_ruta_al_txt_en_la_iteracion,  "\\.txt", "_Corrected.txt") -> new.FileName.path
 
                                            write_delim(DF_ok, path= new.FileName.path, delim = "\t", na = "NA", append = FALSE)
                                            }
```



```{r}
for(i in 1:length(names(my.fpr.DFs))){
  
                                            a.data.study          <- my.fpr.DFs[[i]]
                                            #
                                            my.cols.init.names    <- a.data.study %>% names() %>%
                                            str_extract_all("(^F[0-9]+.*Mean$)|(^B[0-9]+.*Mean$)|(Rgn.*R.*)|(r|g)MeanSignal$|(r|g)BGMedianSignal$") %>% unlist
                                            #
                                            my.cols.init.names %>% str_replace_all('[:whitespace:]|(Rgn.*R.*)', '')  -> my.cols.names.ok
                                            
                                            colnames(my.fpr.DFs[[i]][, my.cols.init.names]) <- my.cols.names.ok
                                            DF_ok <- my.fpr.DFs[[i]]
                                            
                                            names(my.fpr.DFs)[i] -> mi_gsm_en_la_iteracion
                                            
                                            str_extract(archivos_fpr, paste0(".*", mi_gsm_en_la_iteracion, ".*")) %>% 
                                              na.omit() %>% as.character() -> mi_ruta_al_txt_en_la_iteracion
                                            
                                            str_replace(mi_ruta_al_txt_en_la_iteracion,  "\\.txt", "_Corrected.txt") -> new.FileName.path
 
                                            write_delim(DF_ok, path= new.FileName.path, delim = "\t", na = "NA", append = FALSE)
                                            }
```



```{r}
for(i in 1:length(names(my.xml.DFs))){
  
                                            a.data.study          <- my.xml.DFs[[i]]
                                            #
                                            my.cols.init.names    <- a.data.study %>% names() %>%
                                            str_extract_all("(^F[0-9]+.*Mean$)|(^B[0-9]+.*Mean$)|(Rgn.*R.*)|(r|g)MeanSignal$|(r|g)BGMedianSignal$") %>% unlist
                                            #
                                            my.cols.init.names %>% str_replace_all('[:whitespace:]|(Rgn.*R.*)', '')  -> my.cols.names.ok
                                            
                                            colnames(my.xml.DFs[[i]][, my.cols.init.names]) <- my.cols.names.ok
                                            DF_ok <- my.xml.DFs[[i]]
                                            
                                            names(my.xml.DFs)[i] -> mi_gsm_en_la_iteracion
                                            
                                            str_extract(archivos_xml, paste0(".*", mi_gsm_en_la_iteracion, ".*")) %>% 
                                              na.omit() %>% as.character() -> mi_ruta_al_txt_en_la_iteracion
                                            
                                            str_replace(mi_ruta_al_txt_en_la_iteracion,  "\\.txt", "_Corrected.txt") -> new.FileName.path
 
                                            write_delim(DF_ok, path= new.FileName.path, delim = "\t", na = "NA", append = FALSE)
                                            }
```

```{r}
a <-getGEO("GSE1012")
?getGEO
exprs(a$GSE1012_series_matrix.txt.gz)
```












